VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = yes
VIAL_INSECURE = yes
SPLIT_KEYBOARD = yes

EXTRAKEY_ENABLE = yes

TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
ENCODER_ENABLE = yes

RGBLIGHT_ENABLE = yes
RGBLIGHT_ANIMATIONS = no
BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
KEY_OVERRIDE_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
LEADER_ENABLE = no
MOUSEKEY_ENABLE = no
UNICODE_ENABLE = no